Add Gatsby installation to startup docs
primer/components pull request #904
Opened 2020-11-10 21:00 UTC by emplums

Fixes: #903

2020-11-11 16:33 UTC, koddsson commented
Could we install gatsby as a dev dependency instead?

2020-12-04 18:54 UTC, colebemis requested changes

2020-12-04 18:54 UTC, colebemis commented on CONTRIBUTING.md
> +```
```suggestion
Before running the documentation site locally, you'll need to install packages in the root and `docs` directories:

Gatsby is already a dependency in the `docs` site. I think the issue that caused #903 is that the `docs` dependencies weren't installed.
```shell
yarn && cd docs; yarn 
```
```

2020-12-04 19:06 UTC, emplums commented on CONTRIBUTING.md
> +yarn && cd docs; yarn
```suggestion
yarn && cd docs && yarn 
```

2020-12-04 19:07 UTC, emplums commented on CONTRIBUTING.md
> +Then run the following to start up the site:
```suggestion
Then navgiate back to the root folder and run the following to start up the site:
```

2021-01-05 22:54 UTC, merged